/**
 * Angkor Coffee Roasters - Master Product Catalog
 * Authentic Cambodian & Regional High-Altitude Specialty Coffees
 */

const ANGKOR_PRODUCTS = [
  {
    id: 'mondulkiri-peaberry',
    name: 'Mondulkiri Peaberry Reserve',
    tagline: 'Rare single-bean mutation with concentrated sweetness and floral honey aroma',
    category: 'single-origin',
    origin: 'Mondulkiri Highlands, Cambodia',
    altitude: '950m - 1,100m',
    roastLevel: 'Medium',
    roastScore: 3,
    process: 'Wild Honey Processed',
    tastingNotes: ['Wild Honey', 'Dark Cacao', 'Stone Fruit', 'Toasted Macadamia'],
    basePrice: 16.50,
    rating: 4.9,
    reviewsCount: 184,
    badge: 'Best Seller',
    featured: true,
    acidity: 3,
    body: 4,
    sweetness: 5,
    roastProfileNotes: 'Gentle first crack followed by a slow caramelization phase, unlocking floral top-notes with a syrupy mouthfeel.',
    brewMethods: ['V60 Pour Over', 'Aeropress', 'Phin Filter'],
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=700&q=80',
    description: 'Harvested by indigenous Bunong smallholder farmers in the mist-veiled hills of Mondulkiri. Only 5% of each harvest yields naturally fused peaberries, producing an exceptionally round, dense bean that roasts evenly and bursts with wild floral honey and golden stone fruit.'
  },
  {
    id: 'sacred-temple-dark',
    name: 'Angkor Sacred Temple Dark Roast',
    tagline: 'Smoky, deep, and ceremonial with lingering notes of dark molasses and spice',
    category: 'signature',
    origin: 'Mondulkiri & Bolaven Plateau',
    altitude: '1,000m - 1,250m',
    roastLevel: 'Dark',
    roastScore: 5,
    process: 'Slow-Washed & Sun-Dried',
    tastingNotes: ['Smoky Molasses', 'Bittersweet Chocolate', 'Toasted Cardamom', 'Black Pepper'],
    basePrice: 14.50,
    rating: 4.8,
    reviewsCount: 230,
    badge: 'Signature Roast',
    featured: true,
    acidity: 1,
    body: 5,
    sweetness: 3,
    roastProfileNotes: 'Taken just into the second crack with precision drum heat to develop deep roasted oils without bitter char.',
    brewMethods: ['French Press', 'Traditional Phin Filter', 'Cold Brew', 'Moka Pot'],
    image: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=700&q=80',
    description: 'Inspired by ancient temple ceremonies in Siem Reap. We roast these dense highland beans to a rich French dark stage, creating an unapologetically bold, viscous cup designed for sweet condensed milk or a velvety black pour.'
  },
  {
    id: 'ratanakiri-red-earth',
    name: 'Ratanakiri Red Earth Micro-Lot',
    tagline: 'Fermented in volcanic basalt terroir for vibrant tropical sweetness',
    category: 'micro-lot',
    origin: 'Ratanakiri Volcanic Plateau, Cambodia',
    altitude: '1,050m',
    roastLevel: 'Light-Medium',
    roastScore: 2,
    process: '72hr Anaerobic Natural',
    tastingNotes: ['Star Anise', 'Wild Blackberry', 'Sweet Tamarind', 'Palm Sugar'],
    basePrice: 18.00,
    rating: 5.0,
    reviewsCount: 96,
    badge: 'Limited Edition',
    featured: true,
    acidity: 4,
    body: 3,
    sweetness: 5,
    roastProfileNotes: 'Fast drum rotation and low finishing temperature to safeguard the volatile fruit esters and delicate terroir.',
    brewMethods: ['V60 Pour Over', 'Chemex', 'Cold Drip'],
    image: 'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe?auto=format&fit=crop&w=700&q=80',
    description: 'Grown exclusively in the iron-rich red volcanic basalt soils of northeastern Cambodia. Fermented anaerobically inside sealed oak barrels for 72 hours, unlocking exotic tropical fruit nuances that taste like pure sunshine.'
  },
  {
    id: 'bayon-espresso-crema',
    name: 'Bayon Crema Espresso Roast',
    tagline: 'Designed for commercial & home espresso bars with thick golden crema',
    category: 'espresso',
    origin: 'Highland Mondulkiri Arabica & Craft Robusta',
    altitude: '900m - 1,200m',
    roastLevel: 'Medium-Dark',
    roastScore: 4,
    process: 'Natural & Washed Dual-Process',
    tastingNotes: ['Velvet Crema', 'Toasted Almond', 'Ripe Black Fig', 'Cocoa Nibs'],
    basePrice: 15.50,
    rating: 4.9,
    reviewsCount: 312,
    badge: 'Barista Choice',
    featured: true,
    acidity: 2,
    body: 5,
    sweetness: 4,
    roastProfileNotes: 'Balanced roasting curve emphasizing caramelized sucrose compounds for a velvety body and thick, hazelnut-colored crema.',
    brewMethods: ['Espresso Machine', 'Moka Pot', 'Aeropress Espresso Style'],
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=700&q=80',
    description: 'Crafted specifically for the demanding espresso purist. Bayon delivers an irresistible synergy of dense highland Arabica aromatics paired with shade-grown specialty Robusta for immense body and a lingering bittersweet cocoa finish.'
  },
  {
    id: 'siem-reap-sunrise',
    name: 'Siem Reap Sunrise Breakfast Blend',
    tagline: 'Bright, balanced, and uplifting morning roast with sweet citrus & hazelnut',
    category: 'signature',
    origin: 'Mondulkiri & Southern Highlands',
    altitude: '950m',
    roastLevel: 'Medium',
    roastScore: 3,
    process: 'Fully Washed',
    tastingNotes: ['Caramelized Palm Sugar', 'Roasted Hazelnut', 'Kaffir Lime Bloom', 'Milk Chocolate'],
    basePrice: 13.50,
    rating: 4.7,
    reviewsCount: 164,
    badge: 'Popular',
    featured: false,
    acidity: 3,
    body: 3,
    sweetness: 4,
    roastProfileNotes: 'Clean, radiant City roast giving an effortless morning cup with crisp clarity and gentle sweetness.',
    brewMethods: ['Automatic Drip', 'Pour Over', 'French Press'],
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=700&q=80',
    description: 'The definitive dawn roast served at our boutique Siem Reap roastery cafes. Clean and sweet, awakening your senses with notes of organic palm sugar and morning citrus before an adventure through the Angkor temples.'
  },
  {
    id: 'cardamom-wild-arabica',
    name: 'Cardamom Mountain Wild Arabica',
    tagline: 'Rare shade-grown forest coffee from the pristine Cardamom biosphere',
    category: 'single-origin',
    origin: 'Cardamom Mountains, Koh Kong Foothills',
    altitude: '1,200m',
    roastLevel: 'Light',
    roastScore: 1,
    process: 'White Honey',
    tastingNotes: ['Lemongrass Bloom', 'Jasmine Tea', 'Green Apple', 'Raw Wild Honey'],
    basePrice: 19.50,
    rating: 4.9,
    reviewsCount: 82,
    badge: 'Rare Reserve',
    featured: false,
    acidity: 5,
    body: 2,
    sweetness: 5,
    roastProfileNotes: 'Ultra-gentle roast curve preserving organic floral botanicals and crisp green apple acidity.',
    brewMethods: ['Chemex', 'V60 Pour Over', 'Siphon Brewer'],
    image: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=700&q=80',
    description: 'Cultivated under native tropical canopy trees in the protected Cardamom Rainforest corridor. This bean offers breathtaking floral complexity that drinks closer to an exquisite tea than a conventional coffee.'
  },
  {
    id: 'phnom-penh-coldbrew',
    name: 'Phnom Penh Nitro Cold Brew Blend',
    tagline: 'Coarse-roasted micro-lot formulated specifically for 18-hour cold steeping',
    category: 'signature',
    origin: 'Mondulkiri Natural & Bolaven Washed',
    altitude: '900m - 1,150m',
    roastLevel: 'Medium-Dark',
    roastScore: 4,
    process: 'Natural Sun-Cured',
    tastingNotes: ['Chocolate Fudge', 'Vanilla Bean', 'Ceylon Cinnamon', 'Brown Butter'],
    basePrice: 14.00,
    rating: 4.8,
    reviewsCount: 147,
    badge: 'Cold Brew Pick',
    featured: false,
    acidity: 1,
    body: 5,
    sweetness: 5,
    roastProfileNotes: 'Extended development time to maximize lipid extraction and natural sweetness for ice-cold steeping.',
    brewMethods: ['Cold Brew Pitcher', 'Toddy System', 'French Press on Ice'],
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=700&q=80',
    description: 'Formulated to withstand the Southeast Asian heat. Steeped cold over 18 hours, it extracts zero astringency and yields a thick, luscious liquid chocolate essence with real vanilla and cinnamon undertones.'
  },
  {
    id: 'mondulkiri-swiss-water-decaf',
    name: 'Mondulkiri Swiss Water Decaf',
    tagline: '100% chemical-free decaffeination without sacrificing rich flavor',
    category: 'single-origin',
    origin: 'Mondulkiri Highlands, Cambodia',
    altitude: '950m',
    roastLevel: 'Medium',
    roastScore: 3,
    process: '100% Chemical-Free Swiss Water Decaf',
    tastingNotes: ['Milk Chocolate', 'Toasted Malt', 'Sweet Prune', 'Roasted Walnut'],
    basePrice: 17.00,
    rating: 4.7,
    reviewsCount: 65,
    badge: 'Decaf Pure',
    featured: false,
    acidity: 2,
    body: 4,
    sweetness: 4,
    roastProfileNotes: 'Roaster-adjusted conduction profile tailored for decaffeinated cell structures, maintaining rich crema and body.',
    brewMethods: ['All Brew Methods', 'Espresso', 'Pour Over', 'Phin'],
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=700&q=80',
    description: 'Decaffeinated using pure mountain water to gently extract 99.9% of caffeine while leaving origin sugars and terroir completely untouched. Satisfying, deeply comforting, and perfect for sunset sipping.'
  }
];

// Helper functions for products
function getProductById(id) {
  return ANGKOR_PRODUCTS.find(p => p.id === id) || ANGKOR_PRODUCTS[0];
}

function getFeaturedProducts() {
  return ANGKOR_PRODUCTS.filter(p => p.featured);
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { ANGKOR_PRODUCTS, getProductById, getFeaturedProducts };
}
